// Intentionally empty by default.
// Add Drizzle tables here when the site actually needs a database.
// See examples/d1/db/schema.ts for an opt-in example.
import {sqliteTable,text,integer,uniqueIndex,index} from 'drizzle-orm/sqlite-core';
export const games=sqliteTable('games',{id:text('id').primaryKey(),title:text('title').notNull(),developer:text('developer').notNull(),published:text('published').notNull().default(''),announced:text('announced').notNull().default(''),sourceUrl:text('source_url').notNull(),description:text('description').notNull(),createdBy:text('created_by').notNull(),createdAt:text('created_at').notNull()},t=>[uniqueIndex('game_title_source').on(t.title,t.sourceUrl),index('games_created').on(t.createdAt)]);
export const comparisons=sqliteTable('comparisons',{id:text('id').primaryKey(),aId:text('a_id').notNull().references(()=>games.id),bId:text('b_id').notNull().references(()=>games.id),authorId:text('author_id').notNull(),authorName:text('author_name').notNull(),note:text('note').notNull(),analysis:text('analysis').notNull(),createdAt:text('created_at').notNull()},t=>[index('comparison_created').on(t.createdAt),index('comparison_author_time').on(t.authorId,t.createdAt)]);
export const reviews=sqliteTable('reviews',{id:text('id').primaryKey(),comparisonId:text('comparison_id').notNull().references(()=>comparisons.id),userId:text('user_id').notNull(),displayName:text('display_name').notNull(),verdict:text('verdict').notNull(),reason:text('reason').notNull(),updatedAt:text('updated_at').notNull()},t=>[uniqueIndex('one_review_per_account').on(t.comparisonId,t.userId)]);
export const reviewHistory=sqliteTable('review_history',{id:text('id').primaryKey(),comparisonId:text('comparison_id').notNull().references(()=>comparisons.id),userId:text('user_id').notNull(),displayName:text('display_name').notNull(),verdict:text('verdict').notNull(),reason:text('reason').notNull(),createdAt:text('created_at').notNull()},t=>[index('history_comparison_time').on(t.comparisonId,t.createdAt),index('history_user_time').on(t.userId,t.createdAt)]);
export const responses=sqliteTable('responses',{id:text('id').primaryKey(),comparisonId:text('comparison_id').notNull().references(()=>comparisons.id),userId:text('user_id').notNull(),displayName:text('display_name').notNull(),body:text('body').notNull(),sourceUrl:text('source_url').notNull().default(''),createdAt:text('created_at').notNull()},t=>[index('response_comparison_time').on(t.comparisonId,t.createdAt)]);
export const authSessions=sqliteTable('auth_sessions',{tokenHash:text('token_hash').primaryKey(),userId:text('user_id').notNull(),displayName:text('display_name').notNull(),expiresAt:integer('expires_at').notNull()},t=>[index('auth_sessions_expiry').on(t.expiresAt)]);
export const oauthStates=sqliteTable('oauth_states',{stateHash:text('state_hash').primaryKey(),browserHash:text('browser_hash').notNull(),codeVerifier:text('code_verifier').notNull(),returnTo:text('return_to').notNull(),expiresAt:integer('expires_at').notNull()},t=>[index('oauth_states_expiry').on(t.expiresAt)]);
